apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/novatec-mbarrera/data-platform-apps.git"  # Tu repositorio privado
    targetRevision: main
    path: "cert-manager"  # La ruta donde está el Helm Chart de cert-manager
    helm:
      valueFiles:
        - values.yaml  # Archivo con configuraciones personalizadas
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
