apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://charts.jetstack.io"  # Repositorio oficial de Helm
    targetRevision: "v1.14.3"  # Última versión estable (ajusta si es necesario)
    chart: cert-manager
    helm:
      valueFiles:
        - values.yaml  # Archivo con configuraciones personalizadas en el repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
